language: perl

perl:
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

install:
    - perl -e 'print join("\n",@INC)."\n"'
    - dzil authordeps --missing | cpanm  --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - perl -e 'print join("\n",@INC)."\n"'
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
script:
    - dzil test --author --release
